illumineawake/illu-plugins

rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/RooftopAgilityObstacles.java
rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/RooftopAgilityPanel.java
rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/RooftopAgilityPlugin.java

Also changed the Obstacle ctor to create the WorldArea automatically.

Add Canifis course & course list to panel

---

powerskiller/src/main/java/net/runelite/client/plugins/powerskiller/PowerSkillerPlugin.java

added a line to get sleepLength for the plugin overlay.

powerskiller: added line to get sleepDelay for overlay

---

buildSrc/src/main/kotlin/Dependencies.kt
quickeater/src/main/java/net/runelite/client/plugins/quickeater/QuickEaterConfiguration.java
quickeater/src/main/java/net/runelite/client/plugins/quickeater/QuickEaterPlugin.java

added imbued heart reactivation

---

botutils/src/main/java/net/runelite/client/plugins/botutils/BotUtils.java

Gets all of the game objects within a distance specified by the user.

botutils: add getLocalGameObjects function

---

rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/AlchCourse.java
rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/Course.java
rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/RooftopAgilityConfig.java
rooftopagility/src/main/java/net/runelite/client/plugins/rooftopagility/RooftopAgilityPlugin.java

Rooftop agility config fixes

---

quickeater/quickeater.gradle.kts
quickeater/src/main/java/net/runelite/client/plugins/quickeater/QuickEaterPlugin.java

stops quickeater from procing if bank is open

quickeater: don't proc if bank is open

---

iworldwalker/iworldwalker.gradle.kts
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Banks.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Guilds.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Quest.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Skilling.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Slayer.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/iWorldWalkerConfig.java

New in 2.1.1
* 17 New locations across Banks, Guilds, Skilling, and Slayer
* Added Biohazard to quest notes
* Version bump to 2.1.1

iWorldWalker Update 2.1.1

---

iworldwalker/iworldwalker.gradle.kts
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Allotments.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Barcrawl.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Bushes.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Farming.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/FruitTrees.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Herbs.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Hops.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Misc.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Quest.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/Trees.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/iWorldWalkerConfig.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/iWorldWalkerOverlay.java
iworldwalker/src/main/java/net/runelite/client/plugins/iworldwalker/iWorldWalkerPlugin.java

- Added Barcrawl bars (except grand tree one)
- Added a ton of farming patches
- Added Gertrudes Cat
- Added Paterdomus Temple
- Fixed Wizard tower point to outside

Version 2.2.0:

---

ipowerfighter/ipowerfighter.gradle.kts
ipowerfighter/src/main/java/net/runelite/client/plugins/ipowerfighter/iPowerFighterPlugin.java

Report:
Casts high alch on untradables, it alched my xerics talisman and tried to alch other untradebles (herb sack, rune pouch && possibly holy wrench) https://imgur.com/a/SRS7WO7 (sorry for multiple reports it didnt let me paste img in discord)

iPowerFighter: closes bug "Casts high alch on untradables" (discord)

---

ipowerfighter/ipowerfighter.gradle.kts
ipowerfighter/src/main/java/net/runelite/client/plugins/ipowerfighter/iPowerFighterPlugin.java

iPowerFighter: NPE fix

---

ipowerfighter/ipowerfighter.gradle.kts
ipowerfighter/src/main/java/net/runelite/client/plugins/ipowerfighter/iPowerFighterPlugin.java

isTradeable is currently returning everything as untradeable, rolling back until time to check/fix. added some common untradeable to alch blacklist

iPowerFighter: rollback isTradeable check

---

imagiccaster/imagiccaster.gradle.kts
imagiccaster/src/main/java/net/runelite/client/plugins/imagiccaster/iMagicCasterConfig.java
imagiccaster/src/main/java/net/runelite/client/plugins/imagiccaster/iMagicCasterPlugin.java

iMagicCaster: toggle to enable/disable handling of run energy (enabled by default)

iMagicCaster: toggle for run energy

---

botutils/botutils.gradle.kts
botutils/src/main/java/net/runelite/client/plugins/botutils/BotUtils.java
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
iutils/iutils.gradle.kts
iutils/src/main/java/net/runelite/client/plugins/iutils/BankUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/InterfaceUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/InventoryUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/ObjectUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/PlayerUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/WalkUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/iUtils.java

The plugins haven't been updated yet

project: Update iUtils and botutils

---

iquickeater/src/main/java/net/runelite/client/plugins/iquickeater/iQuickEaterConfiguration.java
iquickeater/src/main/java/net/runelite/client/plugins/iquickeater/iQuickEaterPlugin.java

- %hp option to quick eater
- Range on the hp config (1 to 99)
-  nexteathp can change between accounts as well

Added % hp to quick eater and some other changes

---

iquesterfree/iquesterfree.gradle.kts
iquesterfree/src/main/java/net/runelite/client/plugins/iquesterfree/iQuesterFreeConfig.java

Fixed Instructions section, moved buy items option out of instructions.
Preview: https://i.imgur.com/LhBSb0A.png

iQuester Free config tweak

---

iutils/src/main/java/net/runelite/client/plugins/iutils/scripts/UtilsScript.java

check if the inventory contains any of the items rather than chaining the same method together with &&

added boolean inventoryHasItems(boolean any, ItemQuantity... items)

---

iutils/src/main/java/net/runelite/client/plugins/iutils/scripts/UtilsScript.java
iutils/src/main/java/net/runelite/client/plugins/iutils/ui/EquipmentItemStream.java

I think this is right?
- Just expanded the EquipmentItemStream to have similar functionality as InventoryItemStream
- Added equipmentHasItemsID, inventoryHasItemsName, added int/collection <int> compatibility too inventoryHasItems

Easier Item handling

---

iutils/src/main/java/net/runelite/client/plugins/iutils/BankUtils.java

I'm really new to plugin development so this may not be the best approach. Any feedback appreciated

Check if the bank widget is hidden in the event it still exists.

---

buildSrc/src/main/kotlin/Dependencies.kt
iutils/iutils.gradle.kts
iutils/src/main/java/net/runelite/client/plugins/iutils/BankUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/InterfaceUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/InventoryUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/ObjectUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/PlayerUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/WalkUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/iUtils.java

Reverts illumineawake/illu-plugins#121

Revert "Changes to iutils from oprs update"

---

iutils/src/main/java/net/runelite/client/plugins/iutils/PrayerUtils.java

- Get current prayer points
- Check if quick-prayer/specific prayer is active.
- Toggle quick-prayer/specific prayer.

Prayer utils for older utilities.

---

ipowerskiller/src/main/java/net/runelite/client/plugins/ipowerskiller/iPowerSkillerConfiguration.java

changed config of ipowerskiller
create collapsible config sections
set sleep and tick delay sections to be closed by default
moved some settings into ipowerskiller config section
update to 6.1.5

config changes

---

buildSrc/src/main/kotlin/Dependencies.kt

updated dependency version to 4.20.0

updated dependency version

---

ipowerfighter/src/main/java/net/runelite/client/plugins/ipowerfighter/iPowerFighterConfig.java

changed titles to section
put stop conditions in general config and grouped together
put bracelet option in combat section

changed config

---

buildSrc/src/main/kotlin/Dependencies.kt
iutils/iutils.gradle.kts
iutils/src/main/java/net/runelite/client/plugins/iutils/InventoryUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/PlayerUtils.java
iutils/src/main/java/net/runelite/client/plugins/iutils/PrayerUtils.java

Compiled iUtils against latest oprs api after these changes, and the plugins I tested work as normal

Updated to reflect changes from OPRS changes

---

iutils/src/main/java/net/runelite/client/plugins/iutils/iUtils.java

iUtils - added null checks to loadBankInventoryItems() & loadBankItems() to prevent NPE

Added null checks to iUtils to prevent NPE
